# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 74860d9b04ce993d6680ed20996220529459951ee4e009bca8617a9fb8d9f659d0a3a905f98ccba3af71a3601402a42105b065a8c50ddf0b434115343d098e39

test:
  secret_key_base: 5a5aa684f5ffb4ea2927a8ae7f391913d2df719cbd342679f6586179eb393ed5b0c84228a55bc191f485b90736ba1f4544147cd4431d1755f9041c7f4d9f02e2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
